# Adresa noii baze de date
spring.datasource.url=jdbc:mysql://localhost:3306/smarthoreca

# Datele de conectare (XAMPP folose?te utilizatorul 'root' f?r? parol?)
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Îi spunem serverului s? ne creeze automat tabelele
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true